- name: "Get Node.js"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "Install Node.js"
  become: true
  apt:
    name: "nodejs"
    update_cache: yes

- name: "Install pm2"
  npm:
    name: pm2
    global: yes